language: python
python:
  - "3.6"
  - 3.6-dev
  - "3.7"
  - 3.7-dev
  - "3.8"
  - 3.8-dev
  - "3.9"
  - 3.9-dev
  - "3.10"
  - 3.10-dev
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=islatu setup.py test
after_success:
  - coveralls
